### ISSUE TITLE
输入框高度问题

### ISSUE THREAD

**Issue by xiongxiongjiang** [alexiscn/WeChatSwift#2]
你好，我最近也在仿照你的项目写聊天键盘，发现输入框高度并不会随着文字改变而变化，请问有打算解决这个问题吗

**Comment by alexiscn** [comment]
Yes. I am going to refactor chat keyboard in future

**Comment by xiongxiongjiang** [comment]
我放弃了帧布局改用自动布局，勉强写好了。不过还是有个bug。另外，可以告诉我你的联系方式吗，想认识一下

**Comment by alexiscn** [comment]
fixed
