### ISSUE TITLE
iOS 13 中 ASCellNodeBlock 的选中效果好像没了

### ISSUE THREAD

**Issue by webjyh** [alexiscn/WeChatSwift#3]
纯小白一个，在学习的时候，发现 iOS 12下 ASCellNodeBlock 是点击有选中效果的，但是在 iOS 13中就没有了，不知道这是什么原因，想请教下~

**Comment by alexiscn** [comment]
Which function in this project

**Comment by alexiscn** [comment]
Since nothing to do with this project. Close the issue.
